spring:
  application:
    name: service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    validate-on-migrate: false
  jpa:
    hibernate:
        ddl-auto: none
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: service-server
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  url: http://192.168.0.4:8080  # 이게 있어야 함
  port: 8082
solapi:
  api-key: NCSRQPGIRN51K75S
  api-secret : V76OVL09JQXXNZWXAKXYMFMZHGKMKI96
  from-number : 01090244539

cloud:
  aws:
    s3:
      bucket: wimi-dev-storage
    stack:
      auto: false
    region:
      static: ap-northeast-2
   
jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH:public.pem}

file:
  upload-dir: /app/images