-- group_invite
CREATE TABLE public.group_invite (
                                     id bigint NOT NULL,
                                     created_at timestamp(6) without time zone,
                                     expired_at timestamp(6) without time zone,
                                     invited_by character varying(255),
                                     invited_email character varying(255),
                                     inited_user_id character varying(255),
                                     status character varying(255),
                                     group_id bigint
);

ALTER TABLE public.group_invite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_invite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- group_member
CREATE TABLE public.group_member (
                                     id bigint NOT NULL,
                                     group_id bigint,
                                     joined_at timestamp(6) without time zone,
                                     role character varying(255),
                                     status character varying(255),
                                     user_id character varying(255),
                                     CONSTRAINT group_member_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT group_member_status_check CHECK (((status)::text = ANY ((ARRAY['IS_ABLED'::character varying, 'DISABELED'::character varying])::text[])))
);

ALTER TABLE public.group_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_member_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- groups
CREATE TABLE public.groups (
                               id bigint NOT NULL,
                               category character varying(255),
                               created_at timestamp(6) without time zone,
                               created_by character varying(255),
                               description character varying(255),
                               name character varying(255),
                               profile_imgae_url character varying(255),
                               updated_at timestamp(6) without time zone,
                               CONSTRAINT groups_category_check CHECK (((category)::text = ANY ((ARRAY['FAMILY'::character varying, 'FRIEND'::character varying, 'PRIVATE'::character varying])::text[])))
);

ALTER TABLE public.groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- notification
CREATE TABLE public.notification (
                                     id bigint NOT NULL,
                                     body character varying(255),
                                     created_at timestamp(6) without time zone,
                                     is_read boolean,
                                     reference_id bigint,
                                     reference_type character varying(255),
                                     title character varying(255),
                                     type character varying(255),
                                     user_id character varying(255)
);

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- user_summary
CREATE TABLE public.user_summary (
                                     user_id character varying(255) NOT NULL,
                                     nickname character varying(255),
                                     phone_number character varying(255),
                                     description character varying(255),
                                     profile_image_url character varying(255),
                                     role character varying(255),
                                     status character varying(255)
);

-- PK 제약조건
ALTER TABLE ONLY public.group_invite
    ADD CONSTRAINT group_invite_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.group_member
    ADD CONSTRAINT group_member_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_summary
    ADD CONSTRAINT user_summary_pkey PRIMARY KEY (user_id);