-- 1. daily 테이블 생성
CREATE TABLE public.daily (
                              id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              group_id bigint, -- grout_id 오타 수정
                              created_user_id character varying(255),
                              title character varying(255),
                              content text, -- 본문은 내용이 길어질 수 있으므로 text 권장
                              location_tag character varying(255),
                              scope character varying(255),
                              created_at timestamp(6) without time zone,
                              updated_at timestamp(6) without time zone,
                              CONSTRAINT daily_pkey PRIMARY KEY (id),
                              CONSTRAINT fk_daily_group FOREIGN KEY (group_id) REFERENCES public.groups(id)
);

-- 2. daily_image 테이블 생성
CREATE TABLE public.daily_image (
                                    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    daily_id bigint,
                                    url character varying(255),
                                    order_index bigint,
                                    created_at timestamp(6) without time zone,
                                    CONSTRAINT daily_image_pkey PRIMARY KEY (id),
                                    CONSTRAINT fk_daily_image_daily FOREIGN KEY (daily_id) REFERENCES public.daily(id) ON DELETE CASCADE
);

-- 3. daily_comment 테이블 생성
CREATE TABLE public.daily_comment (
                                      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      daily_id bigint,
                                      user_id character varying(255),
                                      parent_id bigint, -- 대댓글용
                                      content character varying(255),
                                      created_at timestamp(6) without time zone,
                                      updated_at timestamp(6) without time zone,
                                      CONSTRAINT daily_comment_pkey PRIMARY KEY (id),
                                      CONSTRAINT fk_daily_comment_daily FOREIGN KEY (daily_id) REFERENCES public.daily(id) ON DELETE CASCADE,
                                      CONSTRAINT fk_daily_comment_user FOREIGN KEY (user_id) REFERENCES public.user_summary(user_id)
);

-- 4. daily_like 테이블 생성
CREATE TABLE public.daily_like (
                                   id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   daily_id bigint,
                                   user_id character varying(255),
                                   created_at timestamp(6) without time zone,
                                   CONSTRAINT daily_like_pkey PRIMARY KEY (id),
                                   CONSTRAINT fk_daily_like_daily FOREIGN KEY (daily_id) REFERENCES public.daily(id) ON DELETE CASCADE,
                                   CONSTRAINT fk_daily_like_user FOREIGN KEY (user_id) REFERENCES public.user_summary(user_id)
);

---------------------------------------------------------
-- 1. 기존 테이블 컬럼명 변경 (ALTER)
---------------------------------------------------------
-- 예: group_invite 테이블의 inited_user_id -> invited_user_id
ALTER TABLE public.group_invite
    RENAME COLUMN inited_user_id TO invited_user_id;

ALTER TABLE public.groups
    RENAME COLUMN profile_imgae_url TO profile_image_url;