-- 1. meeting
CREATE TABLE public.meeting
(
    id              bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title           character varying(255),
    content         text,
    scope           character varying(255),
    group_id        bigint,
    start_at        timestamp(6) without time zone,
    end_at          timestamp(6) without time zone,
    created_at      timestamp(6) without time zone,
    created_user_id character varying(255),
    CONSTRAINT meeting_pkey PRIMARY KEY (id),
    CONSTRAINT fk_meeting_group FOREIGN KEY (group_id)
        REFERENCES public.groups (id)
);

-- 2. meeting_participant
CREATE TABLE public.meeting_participant
(
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    meeting_id bigint,
    user_id    character varying(255),
    status     character varying(50) DEFAULT 'pending',
    CONSTRAINT meeting_participant_pkey PRIMARY KEY (id),
    CONSTRAINT fk_meeting_participant FOREIGN KEY (meeting_id)
        REFERENCES public.meeting (id) ON DELETE CASCADE
);

-- 3. meeting_detail
CREATE TABLE public.meeting_detail
(
    id            bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    meeting_id    bigint,
    detail_type   character varying(50), -- 'place' | 'cost' | 'etc'
    value         character varying(255),
    display_value character varying(255),
    CONSTRAINT meeting_detail_pkey PRIMARY KEY (id),
    CONSTRAINT fk_meeting_detail_meeting FOREIGN KEY (meeting_id)
        REFERENCES public.meeting (id) ON DELETE CASCADE
);